[project]
ref = "your-project-ref"

[functions.rss-feed]
allow_net = [
  "thehackernews.com",
  "krebsonsecurity.com", 
  "www.darkreading.com",
  "www.bleepingcomputer.com",
  "threatpost.com",
  "databreaches.net",
  "therecord.media",
  "www.wired.com",
  "feeds.feedburner.com",
  "feedburner.google.com"
]