// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://krctcrmrejlsinorpgig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyY3Rjcm1yZWpsc2lub3JwZ2lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDAyMjgsImV4cCI6MjA3MTE3NjIyOH0.Z8XgY1dc518Zon7N8tCZ2bv3vwH3cWj-WCLKZ9Uf6T8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);